#%RAML 1.0 NamedExample
oms-exp-response:
  customerId: "0036g000002g2JSAAY"
  saleorderId: "I5TcymDBab2"
  orderNo: "883017241ADFa"
  saleorderType: "Change"
  originalOrder: "Z"
  saleorderStatus: "Placed"
  orderstartDate: 2020-01-15T21:00:00
  orderendDate: 2020-01-15T21:00:00
  promiseDate: 2020-01-15T21:00:00
  filedDate: 2020-01-16T16:37:16