#%RAML 1.0 NamedExample
pim-product:
  productId: "xyz34532"
  productType: "master"
  masterProductId: ""
  productName: "Shirt"
  brand: "Old Navy"
  shortDescription: "This shirt is for men"
  longDescription: "shirt is made up of 90% cotton"
  vendorNumber: "763987"
  vendorName: "Page"
  vendorSku: "zk567435"
  owningCatalogId: "apparel-catalog"
  originalRetailPrice: "100.00"
  taxClassId: "15"
  isSearchable:  "Y"
  priceCurrency: "USD"
  saleUnit: "1"
  minOrderQnty: "1"
  stepQnty: "1"
  inStorePickup: "Y"
  varAttKey1: "size"
  varAttKey2: "color"
  varAttVal1: "30;32;36;40;42"
  varAttVal2: "blue;white;black"
  upc: "zwe765rde"
