#%RAML 1.0 NamedExample
case:
  caseId: "2324"
  isDeleted: false
  masterRecordId: "UBS"
  caseNumber: "5"
  contactId: "3"
  accountId: "1"
  assetId: "2018-12-12"
  sourceId: "123"
  parentId: "2324"
  suppliedName: "Test"
  suppliedEmail: "UBS"
  suppliedPhone: "5"
  suppliedCompany: "3"
  type: "1"
  status: "2018-12-12"
  reason: "123"
  origin: "2324"
  subject: "Test Case"
  priority: "UBS"
  description: "5"
  isClosed: false
  closeDate: "2015-09-28T21:43:36.000Z"
  isEscalated: false
  ownerId: "123"
  createDate: "2015-09-28T21:43:36.000Z"
  createdById: "2018-12-12"
  lastModifiedDate: "2015-09-28T21:43:36.000Z"
  lastModifiedById: "2324"
  systemModStamp: "2015-09-28T21:43:36.000Z"
  contactPhone: "UBS"
  contactMobile: "5"
  contactEmail: "test@test.com"
  contactFax: "1330"
  comments: "2018-12-12"
  lastViewedDate: "2015-09-28T21:43:36.000Z"
  lastReferencedDate: "2015-09-28T21:43:36.000Z"
  externalComments: "5"
  externalStatus: "3"
  externalSystemLastUpdated: "1999-01-01"
  externalOwner: SNOW
  externalPriority: High
  syncToSNOW: true
  syncToJIRA: false