#%RAML 1.0 NamedExample
product:
  brand: "Old Navy"
  creationDate: 2015-07-04T21:00:00
  shortDescription: "This shirt is made up of cotton for business casual"
  longDescription: "Appropriate business casual dress"
  upc:  "azwq12345"
  unit: "100"
  productType : "master"
  owningCatalogId : "apparel-catalog"
  manufacturerName : "Page"
  manufacturerSku : "XED34521"
  name : "Shirt"

