#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/307d6ff5-bca1-42ae-90fd-3d0e4bb68916/ # 
title: Salesforce System API
description: System API for working with SFDC  Object
version: v1
mediaType: application/json

uses: 
  lib: exchange_modules/997d5e99-287f-4f68-bc95-ed435d7c5797/catalyst-library/1.0.45/catalyst-library.raml

types:
  case: !include type/sfdc-case-sys-dataType.raml
  caseResponse: !include type/sfdc-case-resp-dataType.raml


securedBy: [ lib.basicAuthSecurity ]
/case:
  /{caseId}:
    displayName: Case
    get:
      is:
       [lib.trackable, lib.returns-400,lib.returns-404,lib.returns-405,lib.returns-406,lib.returns-415,lib.returns-500,lib.returns-501]
      description: Get case details for the given case ID
      responses: 
            200:
              body: 
                application/json:
                  type: case
    patch:
        is:
         [lib.trackable, lib.returns-400,lib.returns-404,lib.returns-405,lib.returns-406,lib.returns-415,lib.returns-500,lib.returns-501]
        description: Update case object with required fields using case ID
        body:
          application/json:
            type: case
      
                 
        responses: 
            200:
              body: 
                application/json:
                  type: caseResponse
                  