#%RAML 1.0 NamedExample
incident:
  active : "true"
  activityDue : "10/2/2019"
  comments : "This is an example incident"
  commentsAndWorkNotes : "This is an Example Incident"
  description : "This issue is caused due to power outage"
  sfdcCaseId : "5003k00000zSbwPAAS"
  incidentState : "1"
  priority: "1"
  shortDescription: "Power Outage Issue"
  state : "2"