#%RAML 1.0 NamedExample
case:
  caseId: "5003k00000zSuNaAAK"
  caseNumber: ""
  caseOrigin: ""
  caseOwner: ""
  caseReason: "" 
  contactName: "tester"
  type: ""
  subject: "This is a test case"
  active: "false"
  activityDue: ""
  additionalAssigneeList: ""
  approval: ""
  approvalHistory: ""
  approvalSet: ""
  assignedTo: ""
  assignedGroup: ""
  businessDuration: ""
  businessService: ""
  businessStc: ""
  calendarDuration: ""
  calendarStc: "0"
  callerId: ""
  category: ""
  causedBy: ""
  childIncidents: ""
  closeNotes: ""
  closeCode: ""
  closedAt: ""
  closedBy: ""
  cmdbCi: ""
  comments: "This is a test incident"
  commentsAndWorkNotes: ""
  company": ""
  contactType: ""
  correlationDisplay: ""
  correlationId: ""
  deliveryPlan: ""
  deliveryTask: ""
  description: ""
  dueDate: ""
  escalation: ""
  expectedStart: ""
  followUp: ""
  groupList: ""
  holdReason: ""
  impact: ""
  incidentState: "0"
  knowlegde: "false"
  location: ""
  madeSla: "false"
  notify: "0"
  number: ""
  openedAt: ""
  openedBy: ""
  order: "0"
  parent: ""
  parentIncident: ""
  priority: "0"
  problemId: ""
  reassignmentCount: "0"
  reopenCount: "0"
  reopenedBy: ""
  reopenedTime: ""
  resolvedAt: ""
  resolvedBy: ""
  rfc: ""
  severity: "0"
  shortDescription: "This is a test incident"
  slaDue: ""
  state: "New"
  subCategory: ""
  timeWorked": ""
  uponApproval: ""
  uponReject: ""
  urgency: "0"
  userInput: ""
  watchList: ""
  workEnd: ""
  workNotes: ""
  workNotesList: ""
  workStart: ""
  lastUpdatedDate: "2017-07-21T17:32:28Z"
  externalComments: "This is test"
  externalStatus: "In Progress"
  externalSystemLastUpdated: "2017-07-21"
  externalOwner: "Tester"
  externalPriority: "High"
